SET(BM3D_MODULE_NAME_TMP2 ${BM3D_MODULE_NAME})

IF( NOT(OOMOVE3D_CORE) )

SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME}/Graphic)

BM3D_INC_DIR_PROCESS (${BM3D_MODULE_NAME})

BM3D_SRC_SUBDIR_PROCESS(
drawCost.cpp
drawModule.cpp
)

ENDIF()

SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME_TMP2})
