SET(BM3D_MODULE_NAME_TMP ${BM3D_MODULE_NAME})
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME}/dfs)
include_directories (${BM3D_MODULE_NAME}/proto)
include_directories (${BM3D_MODULE_NAME}/include)
BM3D_SRC_SUBDIR_PROCESS(p3d_dfs.cpp p3d_dfsDefaultGraph.cpp p3d_dfsMgGraph.cpp)
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME_TMP})
