/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Fri May 30 00:41:10 2008
 */
#ifndef __CEXTRACT__

extern void g3d_create_hri_planner_form ( void );
extern void g3d_show_hri_planner_form ( void );
extern void g3d_hide_hri_planner_form ( void );
extern void g3d_delete_hri_planner_form ( void );



#endif /* __CEXTRACT__ */
