/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Tue May 12 14:41:50 2009
 */
#ifndef __CEXTRACT__

extern void g3d_create_HRI_affordance_form ( void );
extern void g3d_show_HRI_affordance_form ( void );
extern void g3d_hide_HRI_affordance_form ( void );
extern void g3d_delete_HRI_affordance_form ( void );
extern int CALCULATE_AFFORDANCE;
#endif /* __CEXTRACT__ */
