/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Tue May 27 14:53:23 2008
 */
#ifndef __CEXTRACT__

extern char * gnuplot_get_program_path ( char * pname );
extern gnuplot_ctrl * gnuplot_init ( void );
extern void gnuplot_close ( gnuplot_ctrl * handle );
extern void gnuplot_cmd ( gnuplot_ctrl * handle, char * cmd, ... );
extern void gnuplot_setstyle ( gnuplot_ctrl * h, char * plot_style );
extern void gnuplot_set_xlabel ( gnuplot_ctrl * h, char * label );
extern void gnuplot_set_ylabel ( gnuplot_ctrl * h, char * label );
extern void gnuplot_resetplot ( gnuplot_ctrl * h );
extern void gnuplot_plot_x ( gnuplot_ctrl * handle, double * d, int n, char * title );
extern void gnuplot_plot_xy ( gnuplot_ctrl * handle, double * x, double * y, int n, char * title );
extern void gnuplot_plot_once ( char * title, char * style, char * label_x, char * label_y, double * x, double * y, int n );
extern void gnuplot_plot_slope ( gnuplot_ctrl * handle, double a, double b, char * title );
extern void gnuplot_plot_equation ( gnuplot_ctrl * h, char * equation, char * title );

#endif /* __CEXTRACT__ */
