/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int resName_to_resType ( char *resName, residueTypes *resTypePt );
extern int atomName_to_bkbatomindex ( char *atomName, atomTypes *aType, residueTypes resType );
extern int atomName_to_schatomindex ( char *atomName, atomTypes *aType, residueTypes resType );
extern int number_bkb_atoms ( residueTypes resType );
extern int number_sch_atoms ( residueTypes resType );
extern int get_vdwR_by_type(atomTypes atomType, double* vdwR);
extern int elementName_to_lig_AtomType(char *atomName, atomTypes *atomTypePt);

#endif /* __CEXTRACT__ */
