/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern psf_molecule* init_molecule_struct(char* name);
extern psf_protein* init_protein_struct(char* name);
extern psf_ligand* init_ligand_struct(char* fullName);
extern psf_rigid* init_rigid_struct();
extern psf_joint* init_joint_struct();
extern void free_protein ( psf_protein *protPt );
extern void free_ligand(psf_ligand *ligPt);
extern void free_molecule(psf_molecule *moleculePt);
extern psf_atom *get_N ( psf_residue *resPt );
extern psf_atom *get_CA ( psf_residue *resPt );
extern psf_atom *get_C ( psf_residue *resPt );
extern void get_N_pos ( psf_residue *resPt, double **apos );
extern void get_CA_pos ( psf_residue *resPt, double **apos );
extern void get_C_pos ( psf_residue *resPt, double **apos );
// extern int get_atom_in_list_by_serial(int serial, psf_atom*** theAtom, psf_atom **atomList, int natoms);
extern int psf_get_res_in_list_by_resSeq(int resSeq, psf_residue** theRes, psf_residue **resList, int nresidues);
extern int psf_get_atom_in_list_by_serial(int serial, psf_atom** theAtom, psf_atom **atomList, int natoms);
extern int psf_get_atom_in_list_by_name(int resSeq, char* atomName, psf_atom** theAtom, psf_residue **resList, int nresidues);
extern int psf_get_atom_pos_by_serial(psf_protein* protein, int serial ,double* pos);
extern int psf_get_atom_pos_by_name(psf_protein* protein, int resSeq, char* atomName, double* pos);
extern int psf_get_atom_type_by_serial(psf_protein* protein, int serial , atomTypes* type);
extern int psf_get_atom_type_by_name(psf_protein* protein, int resSeq, char* atomName, int* type);
extern int is_a_defined_serial(int serial, psf_atom **atomList, int natoms);

#endif /* __CEXTRACT__ */
