/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int extract_psf_struct(FILE *pdbfile, char *shortFileName, psf_molecule* molecule);
extern int generate_rigids_in_all_ligands(psf_ligand** ligand_list, int nb_ligands);
extern int load_joint_desc_from_file(const char* fullname, psf_ligand* ligPt);
extern int save_joint_desc_in_file(const char* fullname, psf_ligand* ligPt);

#endif /* __CEXTRACT__ */
