/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Apr 27 10:57:03 2005
 */
#ifndef __CEXTRACT__
#if __STDC__

#else /* __STDC__ */

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
