#!/bin/bash  
move3d-qt-studio -setgui -launch PredictionSimulation -params parameters/params_pipeline_parallel_side_by_side -c pqp -f ../assets/Gesture/HumanPR2Parallel.p3d -sc ../../move3d/assets/Gesture/SCENARIOS/PR2TwoCupsSideParallel.sce
# -launch PredictionSimulation 
# valgrind --tool=memcheck --leak-check=full --error-limit=no 
