#!/bin/bash  
move3d-qt-studio -launch PredictionSimulation -setgui -params parameters/params_pipeline_parallel_facing -c pqp -f ../assets/Gesture/HumanPR2Parallel.p3d -sc ../../move3d/assets/Gesture/SCENARIOS/PR2TwoCupsFacingParallel.sce
# -launch PredictionSimulation
