#!/bin/bash  
move3d-qt-studio -launch PredictionSimulation -setgui -params parameters/params_pipeline_side_by_side -c pqp -f ../assets/Gesture/HumanPR2TwoCups.p3d -sc ../../move3d/assets/Gesture/SCENARIOS/PR2TwoCupsSide.sce
# -launch PredictionSimulation
