#!/bin/bash  
move3d-qt-studio -launch runStomp -setgui -params parameters/params_pr2_human_9 -c pqp -f ../../move3d/assets/CostHriFunction/PR2/Pr2_ShelfAndHuman.p3d -sc ../../move3d/assets/CostHriFunction/PR2/SCENARIOS/Pr2ShelfAndHumanTmp9.sce
