/*
 * Copyright (c) 2001-2014 LAAS/CNRS
 * All rights reserved.
 *
 * Redistribution  and  use  in  source  and binary  forms,  with  or  without
 * modification, are permitted provided that the following conditions are met:
 *
 *   1. Redistributions of  source  code must retain the  above copyright
 *      notice and this list of conditions.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice and  this list of  conditions in the  documentation and/or
 *      other materials provided with the distribution.
 *
 * THE SOFTWARE  IS PROVIDED "AS IS"  AND THE AUTHOR  DISCLAIMS ALL WARRANTIES
 * WITH  REGARD   TO  THIS  SOFTWARE  INCLUDING  ALL   IMPLIED  WARRANTIES  OF
 * MERCHANTABILITY AND  FITNESS.  IN NO EVENT  SHALL THE AUTHOR  BE LIABLE FOR
 * ANY  SPECIAL, DIRECT,  INDIRECT, OR  CONSEQUENTIAL DAMAGES  OR  ANY DAMAGES
 * WHATSOEVER  RESULTING FROM  LOSS OF  USE, DATA  OR PROFITS,  WHETHER  IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR  OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.                                  
 *
 * Siméon, T., Laumond, J. P., & Lamiraux, F. (2001). 
 * Move3d: A generic platform for path planning. In in 4th Int. Symp.
 * on Assembly and Task Planning.
 */
/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern p3d_lin_data * p3d_alloc_spec_lin_localpath ( configPt q_i, configPt q_f );
extern p3d_localpath * p3d_alloc_lin_localpath ( p3d_rob *robotPt, configPt q_i, configPt q_f, int lp_id, int is_valid );
extern double p3d_lin_dist ( p3d_rob *robotPt, p3d_localpath *localpathPt );
extern void p3d_destroy_lin_data ( p3d_rob* robotPt, p3d_lin_data* lin_dataPt );
extern void p3d_lin_destroy ( p3d_rob* robotPt, p3d_localpath* localpathPt );
extern configPt p3d_lin_config_at_distance ( p3d_rob *robotPt, p3d_localpath *localpathPt, double distance );
extern double p3d_lin_stay_within_dist ( p3d_rob* robotPt, p3d_localpath* localpathPt, double parameter, int dir, double *distances );
extern p3d_localpath *p3d_copy_lin_localpath ( p3d_rob* robotPt, p3d_localpath* localpathPt );
extern p3d_localpath *p3d_extract_lin ( p3d_rob *robotPt, p3d_localpath *localpathPt, double l1, double l2 );
extern double p3d_lin_cost ( p3d_rob *robotPt, p3d_localpath *localpathPt );
extern p3d_localpath *p3d_simplify_lin ( p3d_rob *robotPt, p3d_localpath *localpathPt, int *need_colcheck );
extern int p3d_write_lin ( FILE *file, p3d_rob* robotPt, p3d_localpath* localpathPt );
extern void print_LIN ( p3d_rob *robotPt, p3d_localpath *localpathPt );
extern p3d_localpath *p3d_linear_localplanner ( p3d_rob *robotPt, configPt qi, configPt qf, int* ikSol );
extern void lm_destroy_linear_params ( p3d_rob *robotPt, void *paramPt );
extern p3d_localpath *p3d_read_linear_localpath ( p3d_rob *robotPt, FILE *file, double version );

#endif /* __CEXTRACT__ */
