/*
 * Copyright (c) 2001-2014 LAAS/CNRS
 * All rights reserved.
 *
 * Redistribution  and  use  in  source  and binary  forms,  with  or  without
 * modification, are permitted provided that the following conditions are met:
 *
 *   1. Redistributions of  source  code must retain the  above copyright
 *      notice and this list of conditions.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice and  this list of  conditions in the  documentation and/or
 *      other materials provided with the distribution.
 *
 * THE SOFTWARE  IS PROVIDED "AS IS"  AND THE AUTHOR  DISCLAIMS ALL WARRANTIES
 * WITH  REGARD   TO  THIS  SOFTWARE  INCLUDING  ALL   IMPLIED  WARRANTIES  OF
 * MERCHANTABILITY AND  FITNESS.  IN NO EVENT  SHALL THE AUTHOR  BE LIABLE FOR
 * ANY  SPECIAL, DIRECT,  INDIRECT, OR  CONSEQUENTIAL DAMAGES  OR  ANY DAMAGES
 * WHATSOEVER  RESULTING FROM  LOSS OF  USE, DATA  OR PROFITS,  WHETHER  IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR  OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.                                  
 *
 * Siméon, T., Laumond, J. P., & Lamiraux, F. (2001). 
 * Move3d: A generic platform for path planning. In in 4th Int. Symp.
 * on Assembly and Task Planning.
 */
/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern double p3d_rs_compute_range_param ( p3d_localpath *localpathPt );
extern p3d_rs_data * p3d_alloc_spec_rs_localpath ( configPt q_i, configPt q_f, double xcenter, double ycenter, double radius, int dir_rs, double val_rs, int type_rs, pp3d_rs_data next_rs, pp3d_rs_data prev_rs );
extern p3d_localpath *p3d_alloc_rs_localpath ( p3d_rob *robotPt, configPt q_i, configPt q_f, double xcenter, double ycenter, double radius, int dir_rs, double val_rs, int type_rs, int lp_id, pp3d_rs_data next_rs, pp3d_rs_data prev_rs, int is_valid );
extern p3d_localpath * p3d_rs_data_into_localpath ( p3d_rob *robotPt, p3d_rs_data *rs_dataPt, int is_valid, int lp_id );
extern double p3d_length_rs_segment ( p3d_rob *robotPt, p3d_rs_data* rs_dataPt );
extern double p3d_rs_dist ( p3d_rob *robotPt, p3d_localpath *localpathPt );
extern p3d_localpath *p3d_copy_rs_localpath ( p3d_rob* robotPt, p3d_localpath *localpathPt );
extern p3d_localpath *p3d_extract_rs ( p3d_rob *robotPt, p3d_localpath *localpathPt, double l1, double l2 );
extern p3d_localpath *p3d_extract_rs_by_param ( p3d_rob *robotPt, p3d_localpath *localpathPt, double u1, double u2 );
extern void p3d_destroy_rs_data ( p3d_rob* robotPt, p3d_rs_data* rs_dataPt );
extern void p3d_rs_destroy ( p3d_rob* robotPt, p3d_localpath* localpathPt );
extern configPt p3d_rs_config_at_distance ( p3d_rob *robotPt, p3d_localpath *localpathPt, double length );
extern configPt p3d_rs_config_at_param ( p3d_rob *robotPt, p3d_localpath *localpathPt, double param );
extern p3d_rs_data *rs_segment_at_parameter ( p3d_rob *robotPt, p3d_rs_data *rs_segmentPt, double *parameterPt );
extern double p3d_rs_stay_within_dist ( struct rob* robotPt, struct localpath* localpathPt, double parameter, int dir, double* distances );
extern double p3d_rs_cost ( p3d_rob *robotPt, p3d_localpath *localpathPt );
extern p3d_localpath *p3d_simplify_rs ( p3d_rob *robotPt, p3d_localpath *localpathPt, int *need_colcheck );
extern int p3d_write_rs ( FILE *file, p3d_rob* robotPt, p3d_localpath* localpathPt );
extern void print_RS ( p3d_rob *robotPt, p3d_localpath *localpathPt );
extern p3d_localpath *p3d_rsarm_localplanner ( p3d_rob *robotPt, configPt qi, configPt qf, int* ikSol );
extern p3d_localpath *p3d_dubins_localplanner ( p3d_rob *robotPt, configPt qi, configPt qf, int* ikSol );
extern int p3d_create_reeds_shepp_local_method_for_robot ( p3d_rob *robotPt, double *dtab, int *itab );
extern int p3d_create_reeds_shepp_local_method ( double *dtab, int *itab );
extern lm_reeds_shepp_str *lm_create_reeds_shepp ( p3d_rob *robotPt, double *dtab, int *itab );
extern lm_reeds_shepp_str *lm_get_reeds_shepp_lm_param ( p3d_rob* robotPt );
extern void lm_destroy_reeds_shepp_params ( p3d_rob *robotPt, void *local_method_params );
extern p3d_localpath *p3d_read_reeds_shepp_localpath ( p3d_rob *robotPt, FILE *file, double version );

#endif /* __CEXTRACT__ */
