/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern p3d_manh_data * p3d_alloc_spec_manh_localpath ( configPt q_i, configPt q_f, configPt crit_q_i, configPt crit_q_f );
extern p3d_localpath * p3d_alloc_manh_localpath ( p3d_rob *robotPt, configPt q_i, configPt q_f, configPt crit_q_i, configPt crit_q_f, int lp_id, int is_valid );
extern double p3d_manh_dist ( p3d_rob *robotPt, p3d_localpath *localpathPt );
extern void p3d_destroy_manh_data ( p3d_rob* robotPt, p3d_manh_data* manh_dataPt );
extern void p3d_manh_destroy ( p3d_rob* robotPt, p3d_localpath* localpathPt );
extern configPt p3d_manh_config_at_distance ( p3d_rob *robotPt, p3d_localpath *localpathPt, double length );
extern p3d_localpath *p3d_copy_manh_localpath ( p3d_rob* robotPt, p3d_localpath* localpathPt );
extern p3d_localpath *p3d_extract_manh ( p3d_rob *robotPt, p3d_localpath *localpathPt, double l1, double l2 );
extern double p3d_manh_stay_within_dist ( p3d_rob* robotPt, p3d_localpath* localpathPt, double parameter, int dir, double *distances );
extern double p3d_manh_cost ( p3d_rob *robotPt, p3d_localpath *localpathPt );
extern p3d_localpath *p3d_simplify_manh ( p3d_rob *robotPt, p3d_localpath *localpathPt, int *need_colcheck );
extern int p3d_write_manh ( FILE *file, p3d_rob* robotPt, p3d_localpath* localpathPt );
extern p3d_localpath *p3d_manh_localplanner ( p3d_rob *robotPt, configPt qi, configPt qf, int* ikSol );
extern void lm_destroy_manhattan_params ( p3d_rob * robotPt, void *paramPt );
extern p3d_localpath *p3d_read_manhattan_localpath ( p3d_rob* robotPt, FILE *file, double version );

#endif /* __CEXTRACT__ */
