/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int RS_select_curve ( int typ );
extern void RS_get_curve_info ( int *num, Float *t, Float *u, Float *v );
extern Float RS_curve ( pStconfig c_o, pStconfig c_b, Float r, pStcourbe courbe );

#endif /* __CEXTRACT__ */
