/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern double RS_length ( Stconfig *c1, Stconfig *c2, double radius );
extern double reed_shepp ( Stconfig *c1, Stconfig *c2, double radius, int* numero, double *t_r, double *u_r, double *v_r );
extern double reed_shepp48 ( Stconfig *c1, Stconfig *c2, double radius, int numero, double *t_r, double *u_r, double *v_r );
extern double reed_shepp_no_cusp ( Stconfig *c1, Stconfig *c2, double radius, int *numero, double *t_r, double *u_r, double *v_r );
extern double reed_shepp_with_cusp ( Stconfig *c1, Stconfig *c2, double radius, int *numero, double *t_r, double *u_r, double *v_r );
extern double dubins ( Stconfig *c1, Stconfig *c2, double radius, int* numero, double *t_r, double *u_r, double *v_r );

#endif /* __CEXTRACT__ */
