/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int p3d_projectedGradientDescent ( p3d_rob *rob, p3d_strippoint *sp, double d0, configPt q, int *ntest );
extern int p3d_quickGradientDescent ( p3d_rob *rob, p3d_strippoint *sp, double d0, configPt q, int *ntest );

#endif /* __CEXTRACT__ */
