/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int p3d_trackCurrentTraj ( p3d_rob *rob, int Nend, double epsilon, double d0, int Quick );
extern void p3d_gradientDescentOptimize ( p3d_traj *traj, double tend, double epsilon, double d0, int Quick, int (*fct_stop)(void), void (*fct_draw)(void) );
extern void p3d_clearTraj ( p3d_traj *traj, double tend, int (*fct_stop)(void) );

#endif /* __CEXTRACT__ */
