/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern p3d_localpath *p3d_localpath_from_traj ( p3d_localpath *localpathPt, double length, double *distlocPt );
extern int p3d_optim_traj ( p3d_traj *trajPt, double *gain, int *ntest );
extern void p3d_simplify_traj ( p3d_traj *trajPt );

#endif /* __CEXTRACT__ */
