/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern double p3d_test_quality_graph ( p3d_graph *G, int NBTEST );
extern double p3d_test_good_graph ( p3d_graph *G, int NBTEST );

#endif /* __CEXTRACT__ */
