/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int g3d_get_kcd_show_info ( void );
extern void g3d_set_kcd_show_info ( int val );
extern void g3d_set_kcd_draw_all_obbs ( int val );
extern void g3d_set_kcd_draw_robot_obbs ( int val );
extern void g3d_set_kcd_draw_aabb_hier ( int val );
extern void g3d_set_kcd_draw_all_aabbs ( int val );
extern void g3d_kcd_draw_aabb_hier ( void );
extern void g3d_kcd_draw_all_aabbs ( void );
extern void g3d_kcd_draw_nearest_bbs ( void );
extern void g3d_kcd_draw_all_obbs ( int oprngl_context );
extern void g3d_kcd_draw_robot_obbs ( void );
extern void g3d_kcd_draw_closest_points ( void );

#endif /* __CEXTRACT__ */
