/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void g3d_set_draw_coll ( int n );
extern void g3d_reinit_graphics ( void );
extern void g3d_draw ( void );
extern void g3d_draw_obstacles ( G3D_Window* win );
extern void g3d_draw_robots ( G3D_Window *win );
extern void g3d_draw_env_box ( void );
extern void g3d_draw_robot ( int ir, G3D_Window* win );
extern void p3d_drawRobotMoveMeshs(void);

#ifdef PLANAR_SHADOWS
extern void buildShadowMatrix( float fMatrix[16], float fLightPos[4], float fPlane[4] );
extern void g3d_draw_and_col_allwin_active(void);
#endif
#endif /* __CEXTRACT__ */
