IF(QWT)
SET(BM3D_MODULE_NAME_TMP ${BM3D_MODULE_NAME})
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME}/qtHisto)
BM3D_SRC_SUBDIR_PROCESS(
histogramItem.cpp histoWin.cpp
)
include_directories (${BM3D_MODULE_NAME})
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME_TMP})
ENDIF(QWT)
