/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__
 
extern int bio_rrt_E_minimize(double *qs, int *iksols, 
			      int (*fct_stop)(void),void (*fct_draw)(void));
extern void ene_evaluate_traj(void);

#endif /* __CEXTRACT__ */
