/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void g3d_create_main_form ( void );
extern void g3d_loop ( void );
extern void read_scenario_by_name ( const char *file );

#endif /* __CEXTRACT__ */
