/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern pp3d_matrix4 g3d_fct_mobcam_form ( void );

#endif /* __CEXTRACT__ */
