/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void g3d_create_filterbox_form ( int ir );
extern void CB_display_filter_cancel_obj ( FL_OBJECT *ob, long arg );
extern void CB_filter_confirm ( FL_OBJECT *ob, long arg );
extern void CB_filter_cancel ( FL_OBJECT *ob, long arg );
extern void CB_display_filter_ok_obj ( FL_OBJECT *ob, long arg );
extern void g3d_delete_filter_bounds ( int ir );
extern void g3d_delete_filter_cancel ( int ir );
extern void g3d_delete_filter_ok ( int ir );
extern void g3d_delete_filter_form ( int ir );
extern void FORMfilter_init_temp_jntdata( void );

#endif /* __CEXTRACT__ */
