/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int g3d_get_KCD_CHOICE_IS_ACTIVE ( void );
extern void g3d_create_env_form ( void );
extern void g3d_create_volume_slider ( void );
extern void g3d_reinit_volume_slider ( void );
extern void g3d_create_tolerance_slider ( void );
extern void g3d_reinit_tolerance_slider ( void );
extern void g3d_create_dmax_slider ( void );
extern void g3d_create_rel_error_slider ( void );
extern void g3d_reinit_dmax_slider ( void );
extern void g3d_delete_env_form ( void );

#endif /* __CEXTRACT__ */
