/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Jun 23 14:30:06 2004
 */
#ifndef __CEXTRACT__

extern void g3d_create_bio_collision_form ( void );
extern void g3d_delete_bio_collision_form ( void );
extern void afficher_lescollisions ( void );
//extern double get_VdW_pourcent ( void );
double GetPrevVdw(void);
void SetPrevVdw(double prevVdwRadius);
extern int bio_get_flag_evaluate_traj (void );
extern int bio_get_flag_pdb_nodes (void );

#endif /* __CEXTRACT__ */
