/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void g3d_create_rrt_form ( void );
extern void g3d_delete_rrt_form ( void );

#endif /* __CEXTRACT__ */
