/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void g3d_create_planner_form ( void );
extern void CB_global_search_obj(FL_OBJECT *ob, long arg);
extern void CB_specific_search_obj ( FL_OBJECT *ob, long arg );
extern void p3d_printTrajGraphContactPdbFiles(char* filePrefix, int index, p3d_rob *robotPt);
extern void CB_DMAX_param_obj ( FL_OBJECT *ob, long arg );
extern int p3d_get_user_drawnjnt ( void );
extern void p3d_set_user_drawnjnt(int jnt);
extern void CB_stop_obj ( FL_OBJECT *ob, long arg );
extern void CB_del_param_obj ( FL_OBJECT *ob, long arg );
extern void g3d_delete_planner_form ( void );
// TEMPORARY (Juan)
extern int fct_stop(void);
extern void fct_draw(void);
extern void CB_create_drawnjnt_obj(FL_OBJECT *ob, long arg);
extern void CB_print_obj(FL_OBJECT *ob, long arg);
#endif /* __CEXTRACT__ */
