/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void kcd_put_aabb_around_polyh ( void *m3d_poly_it, int guess_of_poly_id, int can_move, int initialization );
extern void kcd_aabb_construct ( void );
extern void kcd_aabb_add ( int nof_bbs_to_add, int tot_nof_boxes );

#endif /* __CEXTRACT__ */
