/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int kcd_gjk_just_intersect ( int box_id1, int nof_vertices1, int *facet_ids1, void *polyh1, int box_id2, int nof_vertices2, int *facet_ids2, void *polyh2, kcd_matrix4 BwrtA, kcd_vector3 *v );
extern int kcd_gjk_intersect_and_common_point ( int box_id1, int nof_vertices1, int *facet_ids1, void *polyh1, int box_id2, int nof_vertices2, int *facet_ids2, void *polyh2, kcd_vector3 *pa, kcd_vector3 *pb, kcd_matrix4 BwrtA, kcd_vector3 *v );
extern int kcd_gjk_closest_pair ( int box_id1, int nof_vertices1, int *facet_ids1, void *polyh1, int box_id2, int nof_vertices2, int *facet_ids2, void *polyh2, kcd_matrix4 AwrtW, kcd_matrix4 BwrtW, kcd_vector3 *pa, kcd_vector3 *pb, double *gjk_distance, double gjk_tolerance );

#endif /* __CEXTRACT__ */
