/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int get_stats_nof_solids ( void );
extern int get_stats_nof_polyhs ( void );
extern int kcd_obb_is_leaf ( kcd_bb *this_obb );
extern int kcd_put_obb_around_polyh ( void *m3d_poly_it, int ext_p_id, int is_mov_obj, int ext_obj_id );
extern void kcd_obb_construct_on_links ( void );

#endif /* __CEXTRACT__ */
