/*
 * Copyright (c) 2001-2014 LAAS/CNRS
 * All rights reserved.
 *
 * Redistribution  and  use  in  source  and binary  forms,  with  or  without
 * modification, are permitted provided that the following conditions are met:
 *
 *   1. Redistributions of  source  code must retain the  above copyright
 *      notice and this list of conditions.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice and  this list of  conditions in the  documentation and/or
 *      other materials provided with the distribution.
 *
 * THE SOFTWARE  IS PROVIDED "AS IS"  AND THE AUTHOR  DISCLAIMS ALL WARRANTIES
 * WITH  REGARD   TO  THIS  SOFTWARE  INCLUDING  ALL   IMPLIED  WARRANTIES  OF
 * MERCHANTABILITY AND  FITNESS.  IN NO EVENT  SHALL THE AUTHOR  BE LIABLE FOR
 * ANY  SPECIAL, DIRECT,  INDIRECT, OR  CONSEQUENTIAL DAMAGES  OR  ANY DAMAGES
 * WHATSOEVER  RESULTING FROM  LOSS OF  USE, DATA  OR PROFITS,  WHETHER  IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR  OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.                                  
 *
 * Siméon, T., Laumond, J. P., & Lamiraux, F. (2001). 
 * Move3d: A generic platform for path planning. In in 4th Int. Symp.
 * on Assembly and Task Planning.
 */
/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int kcd_gjk_just_intersect ( int box_id1, int nof_vertices1, int *facet_ids1, void *polyh1, int box_id2, int nof_vertices2, int *facet_ids2, void *polyh2, kcd_matrix4 BwrtA, kcd_vector3 *v );
extern int kcd_gjk_intersect_and_common_point ( int box_id1, int nof_vertices1, int *facet_ids1, void *polyh1, int box_id2, int nof_vertices2, int *facet_ids2, void *polyh2, kcd_vector3 *pa, kcd_vector3 *pb, kcd_matrix4 BwrtA, kcd_vector3 *v );
extern int kcd_gjk_closest_pair ( int box_id1, int nof_vertices1, int *facet_ids1, void *polyh1, int box_id2, int nof_vertices2, int *facet_ids2, void *polyh2, kcd_matrix4 AwrtW, kcd_matrix4 BwrtW, kcd_vector3 *pa, kcd_vector3 *pb, double *gjk_distance, double gjk_tolerance );

#endif /* __CEXTRACT__ */
