/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void kcd_vectCopy ( kcd_vector3 src, kcd_vector3 dest );
extern void kcd_vectScale ( kcd_vector3 src, kcd_vector3 dest, double k );
extern void kcd_vectAdd ( kcd_vector3 a, kcd_vector3 b, kcd_vector3 c );
extern int kcd_vectEqual ( kcd_vector3 a, kcd_vector3 b );
extern double kcd_vectDotProd ( kcd_vector3 a, kcd_vector3 b );
extern void kcd_vectSub ( kcd_vector3 a, kcd_vector3 b, kcd_vector3 c );
extern double kcd_vectNorm ( kcd_vector3 v );
extern void kcd_vectXprod ( kcd_vector3 a, kcd_vector3 b, kcd_vector3 c );
extern void kcd_mat4Mult ( kcd_matrix4 a, kcd_matrix4 b, kcd_matrix4 c );
extern void kcd_matInvertTransfo ( kcd_matrix4 M, kcd_matrix4 inv );
extern void kcd_matMultTransfo ( kcd_matrix4 a, kcd_matrix4 b, kcd_matrix4 c );
extern void kcd_mat3Copy ( kcd_matrix3 source, kcd_matrix3 dest );
extern void kcd_mat4Copy ( kcd_matrix3 source, kcd_matrix3 dest );
extern void kcd_mat3Add ( kcd_matrix3 a, kcd_matrix3 b, kcd_matrix3 c );
extern void kcd_mat3Transpose ( kcd_matrix3 source, kcd_matrix3 dest );
extern void kcd_Transfo3 ( kcd_matrix3 M, kcd_vector3 x, kcd_vector3 x2 );
extern void kcd_TransfoVect ( kcd_matrix4 M, kcd_vector3 v, kcd_vector3 v2 );
extern void kcd_TransfoPoint ( kcd_matrix4 M, kcd_vector3 p, kcd_vector3 p2 );

#endif /* __CEXTRACT__ */
