/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int enclose_obbs_with_obb_tree ( int group_nr_in_all_bb, int nof_orig_obbs, kcd_bb_p *orig_obbs, kcd_vector3 *the_points, int nb_points, kcd_index_p *the_facet_vertices );
extern void enclose_body_obbs_with_obb_tree ( int group_nr_in_all_bb, int nof_orig_obbs, kcd_bb_p *orig_obbs, kcd_vector3 *the_points, int nb_points, kcd_index_p *the_facet_vertices );

#endif /* __CEXTRACT__ */
