/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void enclose_set_by_aabb ( kcd_vector3 *lofpoints, int nb_vertices, kcd_matrix4 *placement, double *xmin, double *xmax, double *ymin, double *ymax, double *zmin, double *zmax );
extern void enclose_cylinder_by_aabb ( double r1, double h, kcd_matrix4 *placement, double *xmin, double *xmax, double *ymin, double *ymax, double *zmin, double *zmax );
extern void enclose_cone_by_aabb ( double r1, double r2, double h, kcd_matrix4 *placement, double *xmin, double *xmax, double *ymin, double *ymax, double *zmin, double *zmax );

#endif /* __CEXTRACT__ */
