/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int kcd_tri_get_normal ( kcd_vector3 *the_points, int *facet_i_pts, int nb_points, double *A, double *B, double *C );
extern int kcd_tri_get_a_triangle_vertex ( int triangle_nr, int vertex_nr );
extern int kcd_tri_angulate_facet_p ( kcd_vector3 *the_points, int *facet_i_pts, int nb_points, int nr_triangles, tricd_triangulation *tricd_decomp_p );
extern int kcd_tri_angulate_facet_p_i ( kcd_vector3 *the_points, int *facet_i_pts, int nb_points, int nr_triangles, tricd_triangulation *tricd_decomp_p, output_triangle_p *triangle_id_list_p );
extern int kcd_tri_angulate_facet2 ( kcd_vector3 *the_points, int *facet_i_pts, int nb_points, int nr_triangles, tricd_triangulation *tricd_decomp_p, output_triangle_p *triangle_id_list_p, int fill_triangle_id_list );
extern int kcd_tri_angulate_simple_polygon ( kcd_vector3 *the_points, int *facet_i_pts, int nb_points, int *nr_triangles );

#endif /* __CEXTRACT__ */
