/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void kcd_fill_act_grp_pair_arr ( kcd_col_handle * handlePt, int grp_id1, int grp_id2, int kcd_activate );
extern int kcd_get_grp_col_pair_is_act ( kcd_col_handle * handlePt, int grp_id1, int grp_id2 );
extern int kcd_get_grp_col_pair_cur_is_act ( int grp_id1, int grp_id2 );
extern void kcd_fill_act_grp_env_arr ( kcd_col_handle * handlePt, int grp_id, int kcd_activate );
extern int kcd_get_grp_col_env_is_act ( kcd_col_handle * handlePt, int grp_id );
extern int kcd_get_grp_col_env_cur_is_act ( int grp_id );
extern void kcd_fill_act_mo_pair_arr ( kcd_col_handle * handlePt, int mo_id1, int mo_id2, mo_act_type kcd_activate );
extern mo_act_type kcd_get_mo_col_pair_is_act ( kcd_col_handle * handlePt, int mo_id1, int mo_id2 );
extern mo_act_type kcd_get_mo_col_pair_cur_is_act ( int mo_id1, int mo_id2 );
extern void kcd_fill_act_mo_env_arr ( kcd_col_handle * handlePt, int mo_id, mo_act_type kcd_activate );
extern mo_act_type kcd_get_mo_col_env_is_act ( kcd_col_handle * handlePt, int mo_id );
extern mo_act_type kcd_get_mo_col_env_cur_is_act ( int mo_id );
extern kcd_col_handle * kcd_create_col_handle ( int nof_mos, int nof_grps );
extern kcd_col_handle * kcd_copy_col_handle ( kcd_col_handle * handlePt );
extern void kcd_copy_col_handle_into ( kcd_col_handle * src_handlePt, kcd_col_handle * dest_handlePt );
extern void kcd_add_col_handle_into ( kcd_col_handle * src_handlePt, kcd_col_handle * dest_handlePt );
extern void kcd_sub_col_handle_into ( kcd_col_handle * src_handlePt, kcd_col_handle * dest_handlePt );
extern void kcd_deactivate_all_col_handle ( kcd_col_handle * handlePt );
extern void kcd_clean_up_col_handle ( kcd_col_handle * handlePt );
extern int kcd_init_col_table ( int nof_mos, int nof_grps );
extern void kcd_set_cur_col_handle ( kcd_col_handle * handlePt );
extern kcd_col_handle * kcd_get_cur_col_handle ( void );
extern void kcd_clean_up_col_table ( void );
extern void kcd_init_kcd_o_prm_table ( int nof_ext_objs );
extern void kcd_resize_kcd_o_prm_table ( int nof_ext_objs, int nof_extra_ext_objs );
extern void kcd_fill_kcd_o_prm_table ( int kcd_ext_o, int m_or_s_id, int is_movable, int sml_i, int big_i );
extern void kcd_set_active_kcd_o_prm_table ( int ext_obj_id, int set_value );
extern int kcd_get_active_kcd_o_prm_table ( int ext_obj_id );
extern int kcd_get_nof_prm_of_ext_o ( int kcd_ext_o );
extern void kcd_clean_up_kcd_o_prm_table ( int nof_ext_objs );
extern void kcd_init_prim_obj_table ( int tot_nof_prims );
extern void kcd_resize_prim_obj_table ( int tot_nof_prims, int tot_extra_nof_prims );
extern void kcd_fill_prim_obj_table ( int ext_o_id, int ext_p_id, int kcd_o_id, int kcd_p_id, int is_movable );
extern void kcd_clean_up_prim_obj_table ( int tot_nof_prims );
extern int new_kcd_belong_to_same_object ( int ext_p_id1, int ext_p_id2 );
extern void kcd_init_ith_static_obj ( int nof_st_obj );
extern void kcd_resize_ith_static_obj ( int nof_st_obj, int extra_size );
extern void kcd_fill_ith_static_obj ( int kcd_so_id, int ext_obj_id );
extern void kcd_clean_up_ith_static_obj ( int nof_st_obj );
extern void kcd_init_grps ( int nof_mo_grps );
extern void kcd_fill_grps ( int grp_id, int nof_mos_in_grp );
extern int kcd_get_nof_grp_elts ( int grp_id );
extern int kcd_grp_is_active ( int grp_id );
extern void kcd_clean_up_grps ( int nof_mo_grps );
extern void kcd_init_mo_bb_table ( int tot_nof_mos );
extern void kcd_fill_kcd_mo_bb_table ( int ext_o_id, int mobj_id, int bb_id, int grp_id );
extern void kcd_clean_up_mo_bb_table ( int tot_nof_mos );
extern void kcd_init_kcd_poly_bb_table ( int tot_nof_prims );
extern void kcd_resize_kcd_poly_bb_table ( int old_size, int extra_size );
extern void kcd_fill_kcd_poly_bb_table ( int ext_p_id, int prim_bb_id );
extern void kcd_clean_up_poly_bb_table ( int tot_nof_prims );
extern void kcd_init_body_bb_table ( int nof_grps );
extern void kcd_reinit_body_bb_table ( int orig_nof_grps, int nof_to_be_added );
extern void kcd_init_body_bb_table_entry ( int this_entry, int nof_mos );
extern void kcd_fill_body_bb_table_entry ( int grp_id, int *arr_kcd_ids, int nof_mo_ids );
extern int kcd_fill_no_body_bb_table_entry ( void );
extern link_bb_table kcd_get_body_bb_table ( int robot_id, int body_id );
extern void kcd_clean_up_body_bb_table_entry ( int this_entry, int nof_mos );
extern void kcd_clean_up_body_bb_table ( int nof_grps );

#endif /* __CEXTRACT__ */
