/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void kcd_gjk_support_initialize_interesting_seed ( int size_to_allocate );
extern void kcd_gjk_support_resize_interesting_seed ( int orig_size, int size_to_add );
extern void kcd_gjk_set_interesting_seed ( int this_one, int to_this );
extern void kcd_gjk_support_cleanup_interesting_seed ( int size_to_destroy );
extern void kcd_gjk_support ( int kcd_gjk_obj_id, int nof_vertices, int *facet_ids, void *poly, kcd_vector3 gjk_in_vector, kcd_vector3 *support_point );

#endif /* __CEXTRACT__ */
