/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__
#ifdef __STDC__

extern int deltaPrime_off ( FLAT_STR *flatPt, FLAT_LOCAL_PATH_STR *pathPt, double localParam, double *ddelta_v, double *ddelta_w );
extern void deltaPrime_over ( FLAT_STR *flatPt, FLAT_LOCAL_PATH_STR *pathPt, double u, double *deltaPrime_v, double *deltaPrime_w );
extern int flatHilareAccelCoefficient ( FLAT_LOCAL_PATH_STR *pathPt, double localParam, double *coeff );
extern int flatHilareDeltaPrime ( FLAT_LOCAL_PATH_STR *pathPt, double localParam, double *ddelta_v, double *ddelta_w );
extern int flatTrailerAccelCoefficient ( FLAT_STR *flatPt, FLAT_LOCAL_PATH_STR *pathPt, double localParam, double *coeff );
extern void flatTrailerAccelCoefficientTrailer ( FLAT_STR *flatPt, FLAT_LOCAL_PATH_STR *pathPt, double localParam, double *coeff );
extern int flatTrailerDeltaPrime ( FLAT_STR *flatPt, FLAT_LOCAL_PATH_STR *pathPt, double localParam, double *ddelta_v, double *ddelta_w );

#else /* __STDC__ */

extern int deltaPrime_off (/* FLAT_STR *flatPt, FLAT_LOCAL_PATH_STR *pathPt, double localParam, double *ddelta_v, double *ddelta_w */);
extern void deltaPrime_over (/* FLAT_STR *flatPt, FLAT_LOCAL_PATH_STR *pathPt, double u, double *deltaPrime_v, double *deltaPrime_w */);
extern int flatHilareAccelCoefficient (/* FLAT_LOCAL_PATH_STR *pathPt, double localParam, double *coeff */);
extern int flatHilareDeltaPrime (/* FLAT_LOCAL_PATH_STR *pathPt, double localParam, double *ddelta_v, double *ddelta_w */);
extern int flatTrailerAccelCoefficient (/* FLAT_STR *flatPt, FLAT_LOCAL_PATH_STR *pathPt, double localParam, double *coeff */);
extern void flatTrailerAccelCoefficientTrailer (/* FLAT_STR *flatPt, FLAT_LOCAL_PATH_STR *pathPt, double localParam, double *coeff */);
extern int flatTrailerDeltaPrime (/* FLAT_STR *flatPt, FLAT_LOCAL_PATH_STR *pathPt, double localParam, double *ddelta_v, double *ddelta_w */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
