/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Thu Jul 24 10:40:53 2008
 */
#ifndef __CEXTRACT__

extern int gpFriction_cone_contact_plane_intersection ( p3d_vector3 vertex, p3d_vector3 normal, double mu, p3d_plane contactPlane, p3d_vector3 new_normal, double *new_mu );
extern double gpForce_closure_2D_grasp ( double (*contact)[2], double (*normal)[2], double mu[], int nbContacts );
extern double gpForce_closure_3D_grasp ( double (*contact)[3], double (*normal)[3], double mu[], int nbContacts, int nbSlices );

#endif /* __CEXTRACT__ */
