/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Tue Jul  8 16:16:51 2008
 */
#ifndef __CEXTRACT__

extern void readPolyhedron ( p3d_polyhedre *poly, VOLINT_POLYHEDRON *p );
extern void compMassProperties ( VOLINT_POLYHEDRON *p, Mass_properties *mass_prop );
extern void gpCompute_mass_properties ( p3d_polyhedre *poly, Mass_properties *mass_prop );

#endif /* __CEXTRACT__ */
