/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int extend ( rrt_node *tree, double *q, double *qnear, int pas, int *nb_lm, int ext_choice, double *qnew );

#endif /* __CEXTRACT__ */
