/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int start_box ( int pas, int Knum, int (*fct_user)(void), int dist_choice, int connect_choice, int ext_choice, int (*fct_user2)(void) );

#endif /* __CEXTRACT__ */
