/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int connect2tree ( rrt_node **node, rrt_node *tree, rrt_node **rnode1, rrt_node **rnode2, int connect_choice, int *nb_lm, int dist_choice, double env_dist );

#endif /* __CEXTRACT__ */
