/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void save_tree ( char *file );
extern void load_tree ( char *file );
extern void write_tree ( FILE *fich, rrt_graph *graph );
extern void write_comp ( rrt_node *node, int nb, FILE *fich );
extern int read_tree ( FILE *fich, rrt_graph *graph );
extern void charge_tree ( FILE *fich, rrt_graph *graph );

#endif /* __CEXTRACT__ */
