/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void print_distance ( double *q1, double *q2, int dist_choice );
extern void dist_jnt_axe ( double *tab );
extern double calcul_env_dist ( int dist_choice, int pas );
extern double distance_rrt ( double *q1, double *q2, int dist_choice );

#endif /* __CEXTRACT__ */
