SET(BM3D_MODULE_NAME_TMP ${BM3D_MODULE_NAME})
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME}/Greedy)
BM3D_INC_DIR_PROCESS (${BM3D_MODULE_NAME})
BM3D_SRC_SUBDIR_PROCESS(

GreedyCost.cpp
Seeding.cpp
GridCollisionChecker.cpp
CellCollisionChecker.cpp

)
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME_TMP})
