#!/bin/sh
# settings found on http://personal.cscs.ch/~mvalle/mencoder/mencoder.html,
# the webpage of Ing. Mario Valle, Visualization expert in the Swiss National Supercomputing Centre (CSCS)
# Data Analysis & Visualization Services, where many interesting things concerning scientific visualization can be found

opt="vbitrate=3200000:mbd=2:keyint=132:v4mv:vqmin=3:lumi_mask=0.07:dark_mask=0.2:mpeg_quant:scplx_mask=0.1:tcplx_mask=0.1:naq"
mencoder -ovc lavc -lavcopts vcodec=mpeg4:vpass=1:$opt -mf type=jpg:fps=25 -nosound -o /dev/null mf://\*.jpg
mencoder -ovc lavc -lavcopts vcodec=mpeg4:vpass=2:$opt -mf type=jpg:fps=25 -nosound -o output.avi mf://\*.jpg

