
SET(BM3D_MODULE_NAME_TMP ${BM3D_MODULE_NAME})
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME}/PQP)
BM3D_INC_DIR_PROCESS (${BM3D_MODULE_NAME}/include)
BM3D_SRC_SUBDIR_PROCESS(Build.cpp BV.cpp PQP.cpp TriDist.cpp)
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME_TMP})

