all:
	g++ -g pdbnm.cc -o pdbnm


clean:
	rm pdbnm

run:
	./pdbnm -o out -p /home/astefani/BioMove3D/demo/ProteinModels/test/xyl_min.pdb -n /home/astefani/BioMove3D/demo/ProteinModels/test/xyl_min.eigenrtb -v 55 -a 1