/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Sun Apr 13 22:53:05 2008
 */
#ifndef __CEXTRACT__

extern void g3d_draw_rob_pos_area ( void );
extern void g3d_draw_obj_pos_area ( p3d_obj *objPt );
extern void g3d_draw_srchball_pos_area ( double,double,double,double );
extern int p3d_is_pos_area_showed ( p3d_rob *r );
extern int p3d_show_rob_pos_area ( p3d_rob *r );
extern int p3d_hide_rob_pos_area ( p3d_rob *r );
extern int p3d_set_robot_pos_area ( p3d_rob *r, double min, double max, double angle );
extern int p3d_set_allhumans_standard_pos_area ( p3d_rob *r );
extern int p3d_is_in_pos_area ( p3d_rob *r, double x, double y, int isrand );
extern int p3d_is_in_obj_pos_area ( p3d_obj *o, double x, double y );
extern double linearDistance ( double x1, double y1, double x2, double y2 );
extern double rad_angleOf ( double x1, double y1, double x2, double y2 );
extern double rad_angleOf_PIMED ( double x1, double y1, double x2, double y2 );
extern double rad2_angleOf ( double x1, double y1, double x2, double y2 );
extern double get_robot_angle_rad ( p3d_rob *r );

#endif /* __CEXTRACT__ */
