/*   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Sun Apr 13 22:53:05 2008
 */
#ifndef __CEXTRACT__

 extern configPt  g3d_bt_dynamic_tshow(p3d_rob *robotPt, int (*fct)(void), int* nb);


#endif /* __CEXTRACT__ */
