IF(QWT)
SET(BM3D_MODULE_NAME_TMP ${BM3D_MODULE_NAME})
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME}/qtPlot)
BM3D_SRC_SUBDIR_PROCESS(
basicPlot.cpp basicPlotWindow.cpp dataPlot.cpp tempWin.cpp
)
BM3D_INC_DIR_PROCESS (${BM3D_MODULE_NAME})
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME_TMP})
ENDIF(QWT)
