/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Jun 23 14:30:16 2004
 */
#ifndef __CEXTRACT__

extern double euclidian_dist ( const double x1, const double y1, const double z1, const double x2, const double y2, const double z2 );
extern void anim_utils_destroy_buffer ( p3d_rob * Robot, anim_buffer * Buffer );
extern void anim_utils_copy_buffer ( p3d_rob * Robot, anim_buffer * BufferSource, anim_buffer * BufferCible );
extern void anim_selec_robot ( p3d_animlib * FromLib, p3d_animlib * WhereLib, p3d_rob * RobotPt );

#endif /* __CEXTRACT__ */
