/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Jun 23 14:30:11 2004
 */
#ifndef __CEXTRACT__

extern void anim_optim_traj_start ( AnimProb * ZANIM, int NofOptims, int EnableCleanTraj );
extern void anim_optim_traj_initialize ( AnimProb * ZANIM );

#endif /* __CEXTRACT__ */
