/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Jun 23 14:30:10 2004
 */
#ifndef __CEXTRACT__

extern void anim_traj_fct_draw ( void );
extern void anim_compute_path ( AnimProb * ZANIM );

#endif /* __CEXTRACT__ */
