/*
 * Copyright (c) 2001-2014 LAAS/CNRS
 * All rights reserved.
 *
 * Redistribution  and  use  in  source  and binary  forms,  with  or  without
 * modification, are permitted provided that the following conditions are met:
 *
 *   1. Redistributions of  source  code must retain the  above copyright
 *      notice and this list of conditions.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice and  this list of  conditions in the  documentation and/or
 *      other materials provided with the distribution.
 *
 * THE SOFTWARE  IS PROVIDED "AS IS"  AND THE AUTHOR  DISCLAIMS ALL WARRANTIES
 * WITH  REGARD   TO  THIS  SOFTWARE  INCLUDING  ALL   IMPLIED  WARRANTIES  OF
 * MERCHANTABILITY AND  FITNESS.  IN NO EVENT  SHALL THE AUTHOR  BE LIABLE FOR
 * ANY  SPECIAL, DIRECT,  INDIRECT, OR  CONSEQUENTIAL DAMAGES  OR  ANY DAMAGES
 * WHATSOEVER  RESULTING FROM  LOSS OF  USE, DATA  OR PROFITS,  WHETHER  IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR  OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.                                  
 *
 * Siméon, T., Laumond, J. P., & Lamiraux, F. (2001). 
 * Move3d: A generic platform for path planning. In in 4th Int. Symp.
 * on Assembly and Task Planning.
 */
/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Jun 23 14:30:16 2004
 */
#ifndef __CEXTRACT__

extern void CheckPointer ( const void * Pointer, const char * Name );
extern int IsPowerOfTwo ( const unsigned x );
extern unsigned NumberOfBitsNeeded ( unsigned PowerOfTwo );
extern unsigned ReverseBits ( unsigned Index, unsigned NumBits );
extern double Index_to_frequency ( unsigned NumSamples, unsigned Index );
extern void anim_fft_double ( unsigned NofSamples, int InverseTransform, double *RealIn, double *ImagIn, double *RealOut, double *ImagOut );
extern double p3d_fourier_inverse_transform ( int Filter, double NofSamples, double * RealIn, double * ImagIn, double param );
extern double modulo ( double Input, double Mod );
extern void anim_initialize_anim_options_default ( void );
extern void anim_initialize_anim_options ( int a, int b, int c, int d, int e, int f, int g, int h, double i, double j, int k, int l );

#endif /* __CEXTRACT__ */
