/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void anim_load_mcap_file ( const char * FileName, const char RobotName[255] );
extern int anim_load_mldef ( const char * FileName, const char * RobotName );
extern void anim_unload_file ( int AnimId );

#endif /* __CEXTRACT__ */
