/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void anim_col_copy_solution ( AnimProb * ZANIM, configPt solution, int NumBlock );
extern void anim_col_avoidance_step1 ( AnimProb * ZANIM );
extern void anim_col_avoidance_step2 ( AnimProb * ZANIM );
extern void anim_col_avoidance_step3 ( AnimProb * ZANIM );
extern void anim_col_initialize ( AnimProb * ZANIM );

#endif /* __CEXTRACT__ */
