/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Jun 23 14:30:12 2004
 */
#ifndef __CEXTRACT__

extern double anim_sample_path ( AnimProb * ZANIM );
extern void anim_sample_path_initialize ( AnimProb * ZANIM );

#endif /* __CEXTRACT__ */
