/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Jun 23 14:30:15 2004
 */
#ifndef __CEXTRACT__

extern void anim_show_form ( anim_buffer BufferToShow, p3d_rob * RobotPt );

#endif /* __CEXTRACT__ */
