/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Jun 23 14:30:09 2004
 */
#ifndef __CEXTRACT__

extern int anim_joint_is_reactive ( int NumJoint );
extern int anim_reactive_is_initialized ( void );
extern p3d_joint_list * anim_reactive_get_pointer_on_reactive_chain ( int NumChain );
extern void anim_reactive_definition_file ( const char * FileName, p3d_rob * RobotPt );

#endif /* __CEXTRACT__ */
