/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Jun 23 14:30:11 2004
 */
#ifndef __CEXTRACT__

extern int anim_compute_path_stop ( void );
extern void anim_compute_path_interface ( AnimProb * AnimProbPt );

#endif /* __CEXTRACT__ */
