/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Jun 23 14:30:17 2004
 */
#ifndef __CEXTRACT__

extern int bio_set_ik ( p3d_cntrt *ct );
extern int bio_set_ik_nopep ( p3d_cntrt *ct );
extern int bio_compute_ik ( p3d_cntrt *ct, double **sol_configs );
extern int bio_compute_ik_nopep ( p3d_cntrt *ct, double **sol_configs );
extern int bio_compute_ik_nopep_new ( p3d_cntrt *ct, double **sol_configs );
extern void p3d_set_matrix4_values ( p3d_matrix4 M, double m11, double m12, double m13, double m14, double m21, double m22, double m23, double m24, double m31, double m32, double m33, double m34, double m41, double m42, double m43, double m44 );
extern void p3d_rotate_vect_around_axis ( p3d_vector3 axis, double theta, p3d_vector3 v_in, p3d_vector3 v_out );

#endif /* __CEXTRACT__ */
