/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Jun 23 14:30:17 2004
 */
#ifndef __CEXTRACT__

extern int bio_set_track_loop_from_FbFe_sequence( int indJbase, int indJend, char *framestraj_filename );
extern int bio_track_loop_from_FbFe_sequence( void );

extern configPt bio_generate_nearby_random_loop_conf(p3d_rob *robotPt, p3d_cntrt *ctPt, 
						     p3d_matrix4 Fb, p3d_matrix4 Fe, 
						     configPt qp, double max_inc_ang);

#endif /* __CEXTRACT__ */
