/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Jun 23 14:30:17 2004
 */
#ifndef __CEXTRACT__

extern int bio_set_bkb_Hbond(int ifj, int ilj, int index_main_cntrt, 
			     double minNOdist, double maxNOdist, double minHbondang, double maxHbondang);
extern int bio_set_diS_bond(int ifj, int ilj, double minSSdist, double maxSSdist);
extern int bio_get_num_loops( void );
extern int bio_set_loop ( int ifj, int ilj );
extern int bio_set_loop_pos ( int ifj, int ilj, double x, double y, double z, double error );
extern int bio_set_loop_ori ( int ifj, int ilj, int irj );
extern void bio_fix_unfix_loop_end ( p3d_rob *robPt, int onoff );
extern int bio_fixed_loop_end ( void );
extern int bio_set_rlg ( int ctnum, int ifj, int ilj );
extern void bio_set_PRINT_LOOP_GEOM ( int val );
extern int bio_get_PRINT_LOOP_GEOM ( void );
extern void bio_print_loop_geometry ( p3d_cntrt *ct );
extern int bio_set_cyclooctane ( void );
extern int bio_set_cycloheptane ( void );
extern double bio_max_dof_dist_config_backbone_nopep ( p3d_rob * robotPt, configPt q1, configPt q2 );
extern double bio_average_dof_dist_config_backbone_nopep ( p3d_rob * robotPt, configPt q1, configPt q2 );
extern p3d_node* bio_shoot_loop_OLD ( p3d_graph *graphPt );
extern p3d_node* bio_shoot_loop ( p3d_graph *graphPt );
extern int bio_generate_ct_conf( p3d_rob *robotPt, p3d_cntrt *ct, configPt q ); 
extern void bio_loop_graph_statistics ( void );
extern int bio_compute_joint_closure_range(p3d_jnt *jntPt, p3d_cntrt *ctPt, int irlgd, 
					   int *nint, double *intmin, double *intmax);

/* extern int bio_readresind(pp3d_jnt jntPt); */

#endif /* __CEXTRACT__ */
