/*
 * Copyright (c) 2001-2014 LAAS/CNRS
 * All rights reserved.
 *
 * Redistribution  and  use  in  source  and binary  forms,  with  or  without
 * modification, are permitted provided that the following conditions are met:
 *
 *   1. Redistributions of  source  code must retain the  above copyright
 *      notice and this list of conditions.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice and  this list of  conditions in the  documentation and/or
 *      other materials provided with the distribution.
 *
 * THE SOFTWARE  IS PROVIDED "AS IS"  AND THE AUTHOR  DISCLAIMS ALL WARRANTIES
 * WITH  REGARD   TO  THIS  SOFTWARE  INCLUDING  ALL   IMPLIED  WARRANTIES  OF
 * MERCHANTABILITY AND  FITNESS.  IN NO EVENT  SHALL THE AUTHOR  BE LIABLE FOR
 * ANY  SPECIAL, DIRECT,  INDIRECT, OR  CONSEQUENTIAL DAMAGES  OR  ANY DAMAGES
 * WHATSOEVER  RESULTING FROM  LOSS OF  USE, DATA  OR PROFITS,  WHETHER  IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR  OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.                                  
 *
 * Siméon, T., Laumond, J. P., & Lamiraux, F. (2001). 
 * Move3d: A generic platform for path planning. In in 4th Int. Symp.
 * on Assembly and Task Planning.
 */
/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void plus_proche_ligand ( void );
extern void select_plus_proches_paires ( p3d_poly **p1, p3d_poly **p2, int nb_col, p3d_poly ***p1_trunc, p3d_poly ***p2_trunc, int *num );
extern void afficher_les_plus_proches_col ( int num );
extern void afficher_les_non_autocol ( void );
extern void col_tot_moins_autocol ( p3d_poly **p1_tot, p3d_poly **p2_tot, int nb_col_tot, p3d_poly **p1_auto, p3d_poly **p2_auto, int nb_col_auto, p3d_poly ***p1_res, p3d_poly ***p2_res, int *num );
extern void vecteur_for_retract_lig ( p3d_poly **p1, p3d_poly **p2, int nb_col, p3d_vector3 *vect_res );

#endif /* __CEXTRACT__ */
