/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void plus_proche_ligand ( void );
extern void select_plus_proches_paires ( p3d_poly **p1, p3d_poly **p2, int nb_col, p3d_poly ***p1_trunc, p3d_poly ***p2_trunc, int *num );
extern void afficher_les_plus_proches_col ( int num );
extern void afficher_les_non_autocol ( void );
extern void col_tot_moins_autocol ( p3d_poly **p1_tot, p3d_poly **p2_tot, int nb_col_tot, p3d_poly **p1_auto, p3d_poly **p2_auto, int nb_col_auto, p3d_poly ***p1_res, p3d_poly ***p2_res, int *num );
extern void vecteur_for_retract_lig ( p3d_poly **p1, p3d_poly **p2, int nb_col, p3d_vector3 *vect_res );

#endif /* __CEXTRACT__ */
