/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void p3d_autocol_check_integrity ( void );
extern int p3d_init_rob_col_activ ( char *name );
extern int p3d_desactivate_col_check ( char *name_body1, char *name_body2 );
extern int p3d_desactivate_col_check_automatic ( void );
extern int p3d_desactivate_col_check_all ( void );
extern int p3d_autocol_activate_rob ( p3d_rob *rob );
extern void p3d_autocol_destroy_datas ( void );
extern void p3d_autocol_destroy_datas_for_robot ( int index_rob_to_delete );
extern void p3d_autocol_activate_body_pair(int rob_index, int body1, int body2);
extern int p3d_isMarkedForautocol(int rob_index, int body1, int body2);
extern void p3d_setAutocolDeep2(int deep2);

#endif /* __CEXTRACT__ */
