/*
 * Copyright (c) 2001-2014 LAAS/CNRS
 * All rights reserved.
 *
 * Redistribution  and  use  in  source  and binary  forms,  with  or  without
 * modification, are permitted provided that the following conditions are met:
 *
 *   1. Redistributions of  source  code must retain the  above copyright
 *      notice and this list of conditions.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice and  this list of  conditions in the  documentation and/or
 *      other materials provided with the distribution.
 *
 * THE SOFTWARE  IS PROVIDED "AS IS"  AND THE AUTHOR  DISCLAIMS ALL WARRANTIES
 * WITH  REGARD   TO  THIS  SOFTWARE  INCLUDING  ALL   IMPLIED  WARRANTIES  OF
 * MERCHANTABILITY AND  FITNESS.  IN NO EVENT  SHALL THE AUTHOR  BE LIABLE FOR
 * ANY  SPECIAL, DIRECT,  INDIRECT, OR  CONSEQUENTIAL DAMAGES  OR  ANY DAMAGES
 * WHATSOEVER  RESULTING FROM  LOSS OF  USE, DATA  OR PROFITS,  WHETHER  IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR  OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.                                  
 *
 * Siméon, T., Laumond, J. P., & Lamiraux, F. (2001). 
 * Move3d: A generic platform for path planning. In in 4th Int. Symp.
 * on Assembly and Task Planning.
 */
/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void p3d_jacInitialization ( p3d_rob *rob );
extern void p3d_jacDelete ( p3d_rob *rob );
extern int p3d_jacUpdatePosition ( pp3d_rob robotPt );
extern int p3d_jacSetAndUpdatePosition ( p3d_rob *robotPt, configPt q );
extern void p3d_jacUpdateJoint ( p3d_jnt *j );
extern void p3d_jacMult ( p3d_vector3 P, p3d_jnt *jnt, configPt G, p3d_vector3 F );
extern void p3d_jacTransposeMult ( p3d_vector3 P, p3d_jnt *jnt, p3d_vector3 F, configPt G );
extern int p3d_jacPseudoInvMult ( p3d_vector3 P, p3d_jnt *jnt, p3d_vector3 F, configPt G );
extern void jac_rot ( p3d_matrix4 M, p3d_vector3 p, double t );
extern void jac_rot_trans4_rx ( p3d_matrix4 M, double rx, double ry, double rz );
extern void jac_rot_trans4_ry ( p3d_matrix4 M, double rx, double ry, double rz );
extern void jac_rot_trans4_rz ( p3d_matrix4 M, double rx, double ry, double rz );

#endif /* __CEXTRACT__ */
