/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern double p3d_hh_random ( unsigned long int p_i, unsigned long int i );
extern int p3d_getNextHHpoint ( p3d_rob *rob, unsigned long int *hhCount, configPt q, int sample_passive);
extern int p3d_getNextHHpoint_for_q_in_box ( p3d_rob *rob, configPt box_env[], 
					     unsigned long int *hhCount, configPt q, int sample_passive);

#endif /* __CEXTRACT__ */
