/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void p3d_rw_scenario_delete_name ( void );
extern void p3d_rw_scenario_init_name ( void );
extern const char * p3d_rw_scenario_get_name ( void );
extern const char * p3d_rw_scenario_get_path ( void );
extern int p3d_read_scenario ( const char *file );
extern int p3d_save_scenario ( const char *file );

#endif /* __CEXTRACT__ */
