/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void p3d_jacInitialization ( p3d_rob *rob );
extern void p3d_jacDelete ( p3d_rob *rob );
extern int p3d_jacUpdatePosition ( pp3d_rob robotPt );
extern int p3d_jacSetAndUpdatePosition ( p3d_rob *robotPt, configPt q );
extern void p3d_jacUpdateJoint ( p3d_jnt *j );
extern void p3d_jacMult ( p3d_vector3 P, p3d_jnt *jnt, configPt G, p3d_vector3 F );
extern void p3d_jacTransposeMult ( p3d_vector3 P, p3d_jnt *jnt, p3d_vector3 F, configPt G );
extern int p3d_jacPseudoInvMult ( p3d_vector3 P, p3d_jnt *jnt, p3d_vector3 F, configPt G );
extern void jac_rot ( p3d_matrix4 M, p3d_vector3 p, double t );
extern void jac_rot_trans4_rx ( p3d_matrix4 M, double rx, double ry, double rz );
extern void jac_rot_trans4_ry ( p3d_matrix4 M, double rx, double ry, double rz );
extern void jac_rot_trans4_rz ( p3d_matrix4 M, double rx, double ry, double rz );

#endif /* __CEXTRACT__ */
