/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int p3d_read_traj ( const char *file );
extern int p3d_save_traj ( const char *file, p3d_traj * traj );
extern int save_trajectory_without_header(FILE * f, pp3d_traj trajPt);

#endif /* __CEXTRACT__ */
