/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Jun 23 14:30:18 2004
 */
#ifndef __CEXTRACT__

extern void colisiones_aisladas ( int iniA, int nA, int iniB, int nB, char *lA, char *lB );
extern void write_SD_function ( SDpt SD );
extern void write_SD_functions ( void );
extern void general_SD_function ( SDpt SD );
extern void Obb_sc_SD_function ( SDpt SD );
extern void new_inter_bb_SD ( void );
extern void new_Obb_sc_SD ( void );
extern void new_autocol_bb_or_sc_SD ( Rigid_structure *r, p3d_poly **list, SD_function function );
extern void new_sc_bb_SD ( void );
extern void get_init_variables ( void );
extern void create_residual_SDs ( int *autocolindex, int *intercolindex, int *loopindex );

#endif /* __CEXTRACT__ */
