/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void init_confi ( int nrjt, int nr_tests );
extern void clean_up_confi ( int nrjt, int nr_tests );
extern void choose_confi ( int nrjt, int nr_tests );
extern void init_seed ( void );
extern void set_repete ( int seed_val );
extern void set_seed ( int seed_val );
extern void unset_seed ( void );
extern void set_call ( int call_val );
extern void unset_call ( void );
extern void shoot_n_hit ( int nr_tests );
extern void test_current_coll_test ( int nr_tests );
extern void compare_I_V_collide ( int nr_tests );
extern void plan_n_hit ( int what_path );
extern void test_path_coll_test ( void );
extern void compare_I_V_path_collide ( void );
extern void compare_I_V_collide_call_times ( void );
extern void test_current_coll_call_times ( void );
extern void test_upath_coll_test ( void );
extern void compare_I_V_upath_collide ( void );

#endif /* __CEXTRACT__ */
