/*
 * Copyright (c) 2001-2014 LAAS/CNRS
 * All rights reserved.
 *
 * Redistribution  and  use  in  source  and binary  forms,  with  or  without
 * modification, are permitted provided that the following conditions are met:
 *
 *   1. Redistributions of  source  code must retain the  above copyright
 *      notice and this list of conditions.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice and  this list of  conditions in the  documentation and/or
 *      other materials provided with the distribution.
 *
 * THE SOFTWARE  IS PROVIDED "AS IS"  AND THE AUTHOR  DISCLAIMS ALL WARRANTIES
 * WITH  REGARD   TO  THIS  SOFTWARE  INCLUDING  ALL   IMPLIED  WARRANTIES  OF
 * MERCHANTABILITY AND  FITNESS.  IN NO EVENT  SHALL THE AUTHOR  BE LIABLE FOR
 * ANY  SPECIAL, DIRECT,  INDIRECT, OR  CONSEQUENTIAL DAMAGES  OR  ANY DAMAGES
 * WHATSOEVER  RESULTING FROM  LOSS OF  USE, DATA  OR PROFITS,  WHETHER  IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR  OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.                                  
 *
 * Siméon, T., Laumond, J. P., & Lamiraux, F. (2001). 
 * Move3d: A generic platform for path planning. In in 4th Int. Symp.
 * on Assembly and Task Planning.
 */
/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern void init_confi ( int nrjt, int nr_tests );
extern void clean_up_confi ( int nrjt, int nr_tests );
extern void choose_confi ( int nrjt, int nr_tests );
extern void init_seed ( void );
extern void set_repete ( int seed_val );
extern void set_seed ( int seed_val );
extern void unset_seed ( void );
extern void set_call ( int call_val );
extern void unset_call ( void );
extern void shoot_n_hit ( int nr_tests );
extern void test_current_coll_test ( int nr_tests );
extern void compare_I_V_collide ( int nr_tests );
extern void plan_n_hit ( int what_path );
extern void test_path_coll_test ( void );
extern void compare_I_V_path_collide ( void );
extern void compare_I_V_collide_call_times ( void );
extern void test_current_coll_call_times ( void );
extern void test_upath_coll_test ( void );
extern void compare_I_V_upath_collide ( void );

#endif /* __CEXTRACT__ */
