#!/bin/csh -f
#

if($#argv < 2) then 
	echo "Usage: tompeg1 file [otherfiles] megfile";exit;
endif

set N_FILES = `echo "$#argv-1" | bc`
set INPUT_FILES = (${argv[1-$N_FILES]})
set MPEG_FILE = $argv[$#argv]
set PARAM_FILE = .mpg_param_file

if($N_FILES == 1) then
	if(-f $INPUT_FILES) then
		/bin/rm -f mifffiles.miff.*;
		echo "convert +adjoin $INPUT_FILES mifffiles.miff"
		convert +adjoin $INPUT_FILES mifffiles.miff
		set count = 0;
		set MIFF_FILES = ""
		while(-f mifffiles.miff.$count)
			set MIFF_FILES = "$MIFF_FILES mifffiles.miff.$count"
			set count = `echo "$count+1" | bc`
		end
		set count = `echo "$count-1" | bc`
		echo "Conversion done... $count MIFF Frames"
	else
		echo "Image file '$INPUT_FILES' does not exist... Exit"
		exit;
	endif
else 
	set MIFF_FILES = (${INPUT_FILES[1-$#INPUT_FILES]})
	while($#MIFF_FILES > 0)
		if(-f $MIFF_FILES[1]) then
			shift MIFF_FILES
		else
			echo "Image file '$MIFF_FILES[1]' does not exist... Exit"
			exit;	
		endif
	end
	set MIFF_FILES = (${INPUT_FILES[1-$#INPUT_FILES]})
endif

########################################

/bin/rm -f $PARAM_FILE

echo |cat > $PARAM_FILE
echo "PATTERN  IBBBPBBBBP" | cat >> $PARAM_FILE
echo "OUTPUT  $MPEG_FILE" | cat >> $PARAM_FILE
echo "BASE_FILE_FORMAT   PPM" | cat >> $PARAM_FILE
echo 'INPUT_CONVERT $HOME_MOVE3D/bin/script/mifftopnm *'  | cat >> $PARAM_FILE
echo 'GOP_SIZE 30' | cat >> $PARAM_FILE
echo 'SLICES_PER_FRAME  1' | cat >> $PARAM_FILE
echo 'INPUT_DIR .' | cat >> $PARAM_FILE
echo 'PIXEL   HALF' | cat >> $PARAM_FILE
echo 'RANGE   10' | cat >> $PARAM_FILE
echo 'PSEARCH_ALG   LOGARITHMIC' | cat >> $PARAM_FILE
echo 'BSEARCH_ALG   CROSS2' | cat >> $PARAM_FILE
echo 'IQSCALE  8' | cat >> $PARAM_FILE
echo 'PQSCALE  10' | cat >> $PARAM_FILE
echo 'BQSCALE  25' | cat >> $PARAM_FILE
echo 'REFERENCE_FRAME ORIGINAL' | cat >> $PARAM_FILE
echo 'INPUT' | cat >> $PARAM_FILE

set FILE = ($MIFF_FILES)
shift FILE
while($#FILE > 0)
	echo "$FILE[1]" | cat >> $PARAM_FILE
	shift FILE
end
echo END_INPUT | cat >> $PARAM_FILE	



##########################
# cat $PARAM_FILE

/usr/local/imagetools/bin/mpeg_encode $PARAM_FILE

if($N_FILES == 1) then 
	echo $MIFF_FILES
	/bin/rm -f $MIFF_FILES
endif

/bin/rm -f $PARAM_FILE

echo Done!
