#!/usr/local/bin/perl  -- -*-perl-*-

#---------------------------------------------------------------
#  Lit le fichier INPUT et multiplie les longueurs par le facteur 
#  d'echelle specifie.
#---------------------------------------------------------------

# Quelques constantes
$number = '-?\d+\.?\d*[eE]?-?\d*';
$name_obst = '[\w\.\/\-]+';
$name_file = '[\w\.\-]+';

##
## Les parametres
##

if ($#ARGV != 0) {
  die "Usage: macro3d <filein> > out\n";
}

$inputfile = $ARGV[0];

open(INPUT, $inputfile) or
  die "Cannot open input file $inputfile\n";

$compteur = 0;
$obstacle = 0;

while(<INPUT>){
  
  if($obstacle == 0) {

    if (/^(\s*p3d_beg_desc\s+P3D_OBSTACLE\s+)($name_obst)\s+/){
      $obstacle = 1;
      $name = $2;
      $macro = "MACROS/".$name.".macro";
      
      open(OUTPUT, ">".$macro) or
	die "Cannot open output file $macro\n";
      
      print "p3d_read_macro ".$name.".macro ".$name."\n";
      
      print OUTPUT "p3d_beg_desc P3D_OBSTACLE\n";
    }

    else {
      print $_;
    }
  }

  else {
    if (/^\s*p3d_end_desc\s+/){
      $obstacle = 0;
      print OUTPUT $_;
      close(OUTPUT);      
    }
    print OUTPUT $_;
  }
}

close(INPUT);

