SET(BM3D_MODULE_NAME_TMP2 ${BM3D_MODULE_NAME})
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME}/src)
BM3D_SRC_SUBDIR_PROCESS(general_flat.c init_flat.c kinematic_flat.c)
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME_TMP2})
