/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern int EBTInsertNode ( pEBTNode *p_ebt, char *key, int (*fct_order)(void *, void *) );
extern char * EBTFindNode ( pEBTNode ebt, char *key, int (*fct_order)(void *, void *) );
extern int EBTDeleteNode ( pEBTNode *p_ebt, char *key, int (*fct_order)(void *, void *) );
extern char * EBTFindDeleteFirstNode ( pEBTNode *p_ebt );
extern int EBTCheckBalance ( pEBTNode ebt );
extern int EBTHeight ( pEBTNode ebt );
extern int EBTWidth ( pEBTNode ebt );
extern int EBTLength ( pEBTNode ebt );
extern int EBTShowTree ( pEBTNode ebt, void (*print_func)(void *) );

#endif /* __CEXTRACT__ */
