/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

extern double angle_limit_180 ( double angle );
extern double angle_limit_360 ( double angle );
extern double angle_limit_PI ( double angle );
extern double angle_limit_2PI ( double angle );
extern double dist_circle ( double theta1, double theta2 );
extern double diff_angle ( double theta1, double theta2 );

#endif /* __CEXTRACT__ */
