SET(BM3D_MODULE_NAME_TMP ${BM3D_MODULE_NAME})
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME}/rwGraph)
include_directories (${BM3D_MODULE_NAME}/proto)
BM3D_SRC_SUBDIR_PROCESS(p3d_readDefaultGraph.c p3d_readMultiGraph.c p3d_rw_graph.c p3d_rwXmlGraph.c p3d_writeDefaultGraph.c p3d_writeMultiGraph.c)
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME_TMP})
