IF(HRI_COSTSPACE)
SET(BM3D_MODULE_NAME_TMP BM3D_MODULE_NAME)
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME}/HRI_CostSpace)
BM3D_SRC_SUBDIR_PROCESS(

HRICS_CSpace.cpp
HRICS_Distance.cpp
HRICS_HAMP.cpp
HRICS_Planner.cpp
HRICS_old.cpp

)

BM3D_INC_DIR_PROCESS (${BM3D_MODULE_NAME})

include(${CMAKE_SOURCE_DIR}/${BM3D_MODULE_NAME}/Grid/SourceList.cmake)
include(${CMAKE_SOURCE_DIR}/${BM3D_MODULE_NAME}/RRT/SourceList.cmake)
SET(BM3D_MODULE_NAME ${BM3D_MODULE_NAME_TMP})
ENDIF(HRI_COSTSPACE)
