#ifndef __MANIPULATIONSTRUCT_H__
#define __MANIPULATIONSTRUCT_H__

typedef enum MANIPULATION_TASK_TYPE_STR {
  ARM_FREE,
  ARM_PICK_GOTO,
  ARM_PICK_TAKE_TO_FREE,
  ARM_PICK_TAKE_TO_PLACE,
  ARM_PLACE_FROM_FREE
} MANIPULATION_TASK_TYPE_STR;

#endif
