#ifndef FORM_JOINT_LIG_H
#define FORM_JOINT_LIG_H

#ifndef PROTO
#include "forms.h"
#endif

typedef struct {
  FL_FORM *CURRENT_FORM;
  FL_OBJECT *CHOICE;
  FL_OBJECT *BROWSER_ATOMS;
  FL_OBJECT *BROWSER_DIHEDRE;
  FL_OBJECT *FRAME;
  FL_OBJECT *ADD_ATOM[4];
  FL_OBJECT *INPUT_ATOM[4];
  FL_OBJECT *INPUT_VVALUES[2];
  FL_OBJECT *ADD;
  FL_OBJECT *REMOVE;
  FL_OBJECT *FRAME_SAVE_LOAD;
  FL_OBJECT *CHECK_SAVE;
  FL_OBJECT *CHECK_LOAD;
  FL_OBJECT *INPUT_SAVE;
  FL_OBJECT *INPUT_LOAD;
  FL_OBJECT *BROWSE_SAVE;
  FL_OBJECT *BROWSE_LOAD;
  FL_OBJECT *VALIDATE;
  FL_OBJECT *CANCEL;
} JOINT_LIG_FORM;

#endif
