#ifndef FORM_AAA_H
#define FORM_AAA_H

#ifndef PROTO
#include "forms.h"
#endif

#define RIGID_COLOR "@C0" // Black
#define MOBILE_COLOR "@C4" // Blue 

#define MAX_LINE_LENGTH 80

typedef struct {
  FL_FORM *CURRENT_FORM;
  FL_OBJECT *CHOICE;
  FL_OBJECT *BROWSER;
  FL_OBJECT *FRAME;
  FL_OBJECT *TOGGLE_BKB;
  FL_OBJECT *TOGGLE_SCH;
  FL_OBJECT *TOGGLE_ALL_BKB;
  FL_OBJECT *TOGGLE_ALL_SCH;
  FL_OBJECT *FRAME_SAVE_LOAD;
  FL_OBJECT *CHECK_SAVE;
  FL_OBJECT *CHECK_LOAD;
  FL_OBJECT *INPUT_SAVE;
  FL_OBJECT *INPUT_LOAD;
  FL_OBJECT *BROWSE_SAVE;
  FL_OBJECT *BROWSE_LOAD;
  FL_OBJECT *VALIDATE;
  FL_OBJECT *CANCEL;
} AAA_FORM;

#endif
